#!/usr/bin/env bash
# Regenerates Threshold/Rendering/Generated/EmbeddedMetalSources.swift from the
# Metal headers and Shaders.metal. The generated file embeds each source body as
# a Swift raw-string constant so `CustomShaderCompiler` can stitch a self-contained
# Metal source for runtime-compiled `.threshfx` formulas.
#
# Run from the repo root:   ./Scripts/generate_metal_embeds.sh
#
# Re-run whenever ShaderTypes.h, Shaders.metal, or any built-in formula header
# changes — the embedded sources must mirror the static build.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

OUT_DIR="Threshold/Rendering/Generated"
OUT_FILE="$OUT_DIR/EmbeddedMetalSources.swift"
CHECK_ONLY=0
if [[ "${1:-}" == "--check" ]]; then
    CHECK_ONLY=1
elif [[ "${1:-}" != "" ]]; then
    echo "usage: $0 [--check]" >&2
    exit 2
fi
mkdir -p "$OUT_DIR"

emit_block() {
    # $1 = property name, $2 = file path
    local name="$1"
    local file="$2"
    if [[ ! -f "$file" ]]; then
        echo "missing: $file" >&2
        exit 1
    fi
    # Use a triple-quoted Swift raw string with a unique pound-delimiter so source
    # contents (which may contain "" or backslashes) are preserved verbatim.
    printf '    static let %s: String = #"""\n' "$name"
    cat "$file"
    printf '\n"""#\n\n'
}

TMP_FILE="$(mktemp "${TMPDIR:-/tmp}/EmbeddedMetalSources.XXXXXX")"
trap 'rm -f "$TMP_FILE"' EXIT

{
    cat <<'HEADER'
//
//  EmbeddedMetalSources.swift
//  Threshold
//
//  AUTO-GENERATED by Scripts/generate_metal_embeds.sh — DO NOT EDIT BY HAND.
//
//  Bundles the source of every Metal header + Shaders.metal so the runtime
//  shader compiler (CustomShaderCompiler) can build a self-contained Metal
//  library for embedded `.threshfx` distance estimators.
//

import Foundation

enum EmbeddedMetalSources {

HEADER

    emit_block "shaderTypesH"               "Threshold/Rendering/ShaderTypes.h"
    emit_block "fractalFormulaCommonH"      "Threshold/Formulas/FractalFormulaCommon.h"
    emit_block "fractalFormulasH"           "Threshold/Formulas/FractalFormulas.h"

    # Per-formula headers — must be embedded so FractalFormulas.h can reference them.
    emit_block "mandelbulbH"                "Threshold/Formulas/Mandelbulb/Mandelbulb.h"
    emit_block "mengerH"                    "Threshold/Formulas/Menger/Menger.h"
    emit_block "quaternionJuliaH"           "Threshold/Formulas/QuaternionJulia/QuaternionJulia.h"
    emit_block "octahedronH"                "Threshold/Formulas/Octahedron/Octahedron.h"
    emit_block "mengerSphereH"              "Threshold/Formulas/MengerSphere/MengerSphere.h"
    emit_block "theliPseudoKleinianH"       "Threshold/Formulas/TheliPseudoKleinian/TheliPseudoKleinian.h"
    emit_block "kleinianH"                  "Threshold/Formulas/Kleinian/Kleinian.h"

    emit_block "shadersMetal"               "Threshold/Rendering/Shaders.metal"

    cat <<'FOOTER'
}
FOOTER
} > "$TMP_FILE"

if [[ "$CHECK_ONLY" == "1" ]]; then
    if ! cmp -s "$TMP_FILE" "$OUT_FILE"; then
        echo "ERROR: $OUT_FILE is stale. Run Scripts/generate_metal_embeds.sh after editing Metal sources." >&2
        exit 1
    fi
    echo "$OUT_FILE is fresh"
    exit 0
fi

mv "$TMP_FILE" "$OUT_FILE"

echo "Wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
