#!/usr/bin/env bash
# Generates EmbeddedMetalSources.swift from the Metal headers and Shaders.metal.
# Xcode invokes this into each target's DERIVED_FILE_DIR before Swift compilation;
# the generated file is intentionally not checked into the repository.
#
# Standalone inspection: ./Scripts/generate_metal_embeds.sh
# Explicit destination:  ./Scripts/generate_metal_embeds.sh --output /path/file.swift

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

DEFAULT_OUT_DIR="${DERIVED_FILE_DIR:-$REPO_ROOT/.build/Generated}"
OUT_FILE="$DEFAULT_OUT_DIR/EmbeddedMetalSources.swift"
if [[ "${1:-}" == "--output" && -n "${2:-}" && -z "${3:-}" ]]; then
    OUT_FILE="$2"
elif [[ -n "${1:-}" ]]; then
    echo "usage: $0 [--output /path/EmbeddedMetalSources.swift]" >&2
    exit 2
fi
mkdir -p "$(dirname "$OUT_FILE")"

emit_block() {
    # $1 = property name, $2 = file path
    local name="$1"
    local file="$2"
    if [[ ! -f "$file" ]]; then
        echo "missing: $file" >&2
        exit 1
    fi
    # Use a triple-quoted Swift raw string with a unique pound-delimiter so source
    # contents (which may contain "" or backslashes) are preserved verbatim.
    printf '    static let %s: String = #"""\n' "$name"
    cat "$file"
    printf '\n"""#\n\n'
}

TMP_FILE="$(mktemp "${TMPDIR:-/tmp}/EmbeddedMetalSources.XXXXXX")"
trap 'rm -f "$TMP_FILE"' EXIT

{
    cat <<'HEADER'
//
//  EmbeddedMetalSources.swift
//  Threshold
//
//  AUTO-GENERATED by Scripts/generate_metal_embeds.sh — DO NOT EDIT BY HAND.
//
//  Bundles the source of every Metal header + Shaders.metal so the runtime
//  shader compiler (CustomShaderCompiler) can build a self-contained Metal
//  library for embedded `.threshfx` distance estimators.
//

import Foundation

enum EmbeddedMetalSources {

HEADER

    emit_block "shaderTypesH"               "Threshold/Rendering/ShaderTypes.h"
    emit_block "fractalFormulaCommonH"      "Threshold/Formulas/FractalFormulaCommon.h"
    emit_block "fractalFormulasH"           "Threshold/Formulas/FractalFormulas.h"

    # Per-formula headers — must be embedded so FractalFormulas.h can reference them.
    emit_block "mandelbulbH"                "Threshold/Formulas/Mandelbulb/Mandelbulb.h"
    emit_block "mengerH"                    "Threshold/Formulas/Menger/Menger.h"
    emit_block "quaternionJuliaH"           "Threshold/Formulas/QuaternionJulia/QuaternionJulia.h"
    emit_block "octahedronH"                "Threshold/Formulas/Octahedron/Octahedron.h"
    emit_block "mengerSphereH"              "Threshold/Formulas/MengerSphere/MengerSphere.h"
    emit_block "theliPseudoKleinianH"       "Threshold/Formulas/TheliPseudoKleinian/TheliPseudoKleinian.h"
    emit_block "kleinianH"                  "Threshold/Formulas/Kleinian/Kleinian.h"

    emit_block "shadersMetal"               "Threshold/Rendering/Shaders.metal"

    cat <<'FOOTER'
}
FOOTER
} > "$TMP_FILE"

if [[ -f "$OUT_FILE" ]] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
    echo "$OUT_FILE is fresh"
else
    mv "$TMP_FILE" "$OUT_FILE"
    echo "Wrote $OUT_FILE ($(wc -l < "$OUT_FILE") lines)"
fi
